server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git: 
          defaul-label: eureka
          uri: https://github.com/ferreiraMarques/microservice-config-test
          search-paths: config-data
          
application:
  name: config-service
            
      
